DROP TABLE IF EXISTS "lot";
CREATE TABLE lot (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    address TEXT,
--    city TEXT,  -- These three are constants, no need to duplicate here
--    st TEXT,
--    zip TEXT,
    closing_date INTEGER,
    note TEXT,
    fk_curr_owner INTEGER,
    fk_prev_owner INTEGER --,
--    FOREIGN KEY(fk_curr_owner) REFERENCES owner(id)
--    FOREIGN KEY(fk_prev_owner) REFERENCES owner(id)
);
INSERT INTO "lot" VALUES(1,'3241 Windwood Trails Drive',NULL,NULL,NULL,NULL);
INSERT INTO "lot" VALUES(2,'3245 Windwood Trails Drive',NULL,NULL,NULL,NULL);
INSERT INTO "lot" VALUES(3,'3249 Windwood Trails Drive',NULL,NULL,NULL,NULL);
INSERT INTO "lot" VALUES(4,'1148 Monza Drive',NULL,NULL,NULL,NULL);
INSERT INTO "lot" VALUES(5,'1153 Monza Drive',NULL,NULL,NULL,NULL);
INSERT INTO "lot" VALUES(6,'1157 Monza Drive',NULL,NULL,NULL,NULL);
INSERT INTO "lot" VALUES(7,'1161 Monza Drive',NULL,NULL,NULL,NULL);
INSERT INTO "lot" VALUES(8,'1165 Monza Drive',NULL,NULL,NULL,NULL);
INSERT INTO "lot" VALUES(9,'1169 Monza Drive',NULL,NULL,NULL,NULL);
INSERT INTO "lot" VALUES(10,'1173 Monza Drive',NULL,NULL,NULL,NULL);
INSERT INTO "lot" VALUES(11,'1177 Monza Drive',NULL,NULL,NULL,NULL);
INSERT INTO "lot" VALUES(12,'1181 Monza Drive',NULL,NULL,NULL,NULL);
INSERT INTO "lot" VALUES(13,'1180 Monza Drive',NULL,NULL,NULL,NULL);
INSERT INTO "lot" VALUES(14,'1176 Monza Drive',NULL,NULL,NULL,NULL);
INSERT INTO "lot" VALUES(15,'1172 Monza Drive',NULL,NULL,NULL,NULL);
INSERT INTO "lot" VALUES(16,'1168 Monza Drive',NULL,NULL,NULL,NULL);
INSERT INTO "lot" VALUES(17,'1164 Monza Drive',NULL,NULL,NULL,NULL);
INSERT INTO "lot" VALUES(18,'1160 Monza Drive',NULL,NULL,NULL,NULL);
INSERT INTO "lot" VALUES(19,'3244 Windwood Trails Drive',NULL,NULL,NULL,NULL);
INSERT INTO "lot" VALUES(20,'3240 Windwood Trails Drive',NULL,NULL,NULL,NULL);
INSERT INTO "lot" VALUES(21,'3284 Hyatt Court',NULL,NULL,NULL,NULL);
INSERT INTO "lot" VALUES(22,'3282 Hyatt Court',NULL,NULL,NULL,NULL);
INSERT INTO "lot" VALUES(23,'3280 Hyatt Court',NULL,NULL,NULL,NULL);
INSERT INTO "lot" VALUES(24,'3278 Hyatt Court',NULL,NULL,NULL,NULL);
INSERT INTO "lot" VALUES(25,'3276 Hyatt Court',NULL,NULL,NULL,NULL);
INSERT INTO "lot" VALUES(26,'3274 Hyatt Court',NULL,NULL,NULL,NULL);
INSERT INTO "lot" VALUES(27,'3272 Hyatt Court',NULL,NULL,NULL,NULL);
INSERT INTO "lot" VALUES(28,'3270 Hyatt Court',NULL,NULL,NULL,NULL);
INSERT INTO "lot" VALUES(29,'3268 Hyatt Court',NULL,NULL,NULL,NULL);
INSERT INTO "lot" VALUES(30,'3266 Hyatt Court',NULL,NULL,NULL,NULL);
INSERT INTO "lot" VALUES(31,'3264 Hyatt Court',NULL,NULL,NULL,NULL);
INSERT INTO "lot" VALUES(32,'3262 Hyatt Court',NULL,NULL,NULL,NULL);
INSERT INTO "lot" VALUES(33,'3260 Hyatt Court',NULL,NULL,NULL,NULL);
INSERT INTO "lot" VALUES(34,'3258 Hyatt Court',NULL,NULL,NULL,NULL);
INSERT INTO "lot" VALUES(35,'3256 Hyatt Court',NULL,NULL,NULL,NULL);
INSERT INTO "lot" VALUES(36,'3254 Hyatt Court',NULL,NULL,NULL,NULL);
INSERT INTO "lot" VALUES(37,'3252 Hyatt Court',NULL,NULL,NULL,NULL);
INSERT INTO "lot" VALUES(38,'3250 Hyatt Court',NULL,NULL,NULL,NULL);
INSERT INTO "lot" VALUES(39,'3251 Hyatt Court',NULL,NULL,NULL,NULL);
INSERT INTO "lot" VALUES(40,'3253 Hyatt Court',NULL,NULL,NULL,NULL);
INSERT INTO "lot" VALUES(41,'3255 Hyatt Court',NULL,NULL,NULL,NULL);
INSERT INTO "lot" VALUES(42,'3257 Hyatt Court',NULL,NULL,NULL,NULL);
INSERT INTO "lot" VALUES(43,'1424 Westin Drive',NULL,NULL,NULL,NULL);
INSERT INTO "lot" VALUES(44,'1416 Westin Drive',NULL,NULL,NULL,NULL);
INSERT INTO "lot" VALUES(45,'1408 Westin Drive',NULL,NULL,NULL,NULL);
INSERT INTO "lot" VALUES(46,'3208 Windwood Trails Drive',NULL,NULL,NULL,NULL);
INSERT INTO "lot" VALUES(47,'3204 Windwood Trails Drive',NULL,NULL,NULL,NULL);
INSERT INTO "lot" VALUES(48,'3200 Windwood Trails Drive',NULL,NULL,NULL,NULL);
INSERT INTO "lot" VALUES(49,'1401 Westin Drive',NULL,NULL,NULL,NULL);
INSERT INTO "lot" VALUES(50,'3216 Windwood Trails Drive',NULL,NULL,NULL,NULL);
INSERT INTO "lot" VALUES(51,'3220 Windwood Trails Drive',NULL,NULL,NULL,NULL);
INSERT INTO "lot" VALUES(52,'3224 Windwood Trails Drive',NULL,NULL,NULL,NULL);
INSERT INTO "lot" VALUES(53,'3228 Windwood Trails Drive',NULL,NULL,NULL,NULL);
INSERT INTO "lot" VALUES(54,'3232 Windwood Trails Drive',NULL,NULL,NULL,NULL);
INSERT INTO "lot" VALUES(55,'3287 Hyatt Court',NULL,NULL,NULL,NULL);
INSERT INTO "lot" VALUES(56,'3283 Hyatt Court',NULL,NULL,NULL,NULL);
INSERT INTO "lot" VALUES(57,'3279 Hyatt Court',NULL,NULL,NULL,NULL);
INSERT INTO "lot" VALUES(58,'3275 Hyatt Court',NULL,NULL,NULL,NULL);
INSERT INTO "lot" VALUES(59,'12 Ritz Court',NULL,NULL,NULL,NULL);
INSERT INTO "lot" VALUES(60,'10 Ritz Court',NULL,NULL,NULL,NULL);
INSERT INTO "lot" VALUES(61,'8 Ritz Court',NULL,NULL,NULL,NULL);
INSERT INTO "lot" VALUES(62,'6 Ritz Court',NULL,NULL,NULL,NULL);
INSERT INTO "lot" VALUES(63,'4 Ritz Court',NULL,NULL,NULL,NULL);
INSERT INTO "lot" VALUES(64,'3263 Hyatt Court',NULL,NULL,NULL,NULL);
INSERT INTO "lot" VALUES(65,'3259 Hyatt Court',NULL,NULL,NULL,NULL);
INSERT INTO "lot" VALUES(66,'1425 Westin Drive',NULL,NULL,NULL,NULL);
INSERT INTO "lot" VALUES(67,'1417 Westin Drive',NULL,NULL,NULL,NULL);
INSERT INTO "lot" VALUES(68,'1409 Westin Drive',NULL,NULL,NULL,NULL);
